### ISSUE TITLE
Bistå Booking med å migrere DNS

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#100]
### Beskrivelse

Når Booking skal ta i bruk det nye prod-miljøet må https://booking.oslo.kommune.no/ settes til å peke på dette. 

### Motivasjon

Booking er i ferd med å migrere til brolagt sti. De har en ekstern url som brukes i løsningen, og i forbindelse med migreringen må denne oppdateres til å peke på det nye miljøet (når alt er klart).

Det er en liten usikkerhet i hvordan man går frem for å få URL'en til å peke på nytt miljø. Dette må sjekkes ut slik at oppskriften er klar til migreringsdagen, og for å sikre at alle steg som skal gjøres på forhånd er gjort.

Vi hjelper Booking med dette siden vi er opptatt av at de skal komme seg over i tide, og vil derfor hjelpe til med å fjerne hindringer.

**Comment by leiacf** [comment]
https://booking.oslo.kommune.no/ peker på https://public.booking-prod.oslo.systems/

**Comment by yngvark** [comment]
Dagens oppsett:

booking.oslo.kommune.no peker på NS-records for hosted zone booking.oslo.kommune.no i [Route53](https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z06095503PIN5ZKI53QQV).

I denne hosted zonen er det ulike A-records for frontends for booking:
* booking.oslo.kommune.no -> ALB med tag booking-public
* admin.booking.oslo.kommune.no -> ALB med tag booking-admin
* temptest.booking.oslo.kommune.no -> Ikke-eksisterende ALB såvidt jeg kan se.

To mulige approacher:

For å slippe å touche ting Okctl har satt opp, mao. få mindre kompleksitet ifbm. med migrering, er det enkleste dersom brolagt sti setter opp en ny hosted zone, feks booking-prod-something.oslo.systems.

Da kan vi bare endre A-records i booking.oslo.kommune.no hosted zone til nye ALB-er fra golden path oppsett.

Dersom Booking ønsker å beholde booking-prod.oslo.systems DNS-en, så må vi
* Importere denne i Terraform i golden path oppsettet. ToDo finne ut nøyaktig hvordan man gjør dette. Det krever nok litt `terraform import`.
* Sørge for å ikke bruke `okctl delete cluster` for å ta ned booking prod cluster, da denne river ned denne Hosted zonen.

**Comment by yngvark** [comment]
ToDo: Sjekk hva TTL på relevante DNS records er.

**Comment by yngvark** [comment]
TTL er 60 sekunder.

Detaljer:

TTL på A-recods for HZ booking.oslo.kommune.no vises slik:
![image](https://user-images.githubusercontent.com/562343/214878918-69774b09-704d-4150-a740-703bc01c81e5.png)

Og forklares slik i [dok](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html):

> If an alias record points to an AWS resource, you can't set the time to live (TTL); Route 53 uses the default TTL for the resource.

[Og](https://aws.amazon.com/route53/faqs/):

> Alias records which have fixed TTL of 60 seconds

Se også: https://stackoverflow.com/a/52487109

**Comment by yngvark** [comment]
@haavardeide og jeg gikk igjennom oppsettet for DNS og rutinger til Booking nå. Noen funn:

- public-lb -> listener for 443 mangler Listener rules tilsvarende de man finner for ALB `k8s-booking-bookingp-e92e5faa35` (regel for `/api/*` er den sentrale, for å route til backend i stedet for frontend).
  - Husk å bruke Terraform framfor clickops
  - Bakgrunn: Dette trengs for å unngå Cross domain sikkerhetskrav i frontend.

- booking.oslo.kommune.no bør inn i Terraform. Dette kan gjøres på sikt, trengs ikke gjøres nå.

- Man kan teste med et nytt A-record for å teste på forhånd.

**Comment by yngvark** [comment]
La inn kommentar om SNI i endelig løsningsforslag, det mangla.

**Comment by yngvark** [comment]
Da er alt ferdig, migrering funka.
