### ISSUE TITLE
Rotere Oauth token for Azure AD brukersynk

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#102]
# Beskrivelse

* [x] Finn ut hva som må gjøres mot UKE for å få rotert dette.
  * Se runbook.
* [x] Lag runbook som forklarer hvordan man roterer token
  * Runbook: https://docs.google.com/document/d/16sDzpuf5Mb5xwZkFsSkUf7ND-2e9M7lhRY4EFYQ2T9Q/edit#
* [x] Rotere token
* [x] Siden dette må gjøres en gang i året, og det er temmelig viktig at vi ikke glemmer det, finn et system som gjør at vi husker på denne oppgaven hvert år. (Feks reminder på Slack og noe annet, etc, etc). Og gjerne en dobbeltsjekk.
  * Vi har nå årlig påminnelse i Slack.
  * Vi har nå årlig event i Outlook.

# Motivasjon

Sørge for at brukersynk mot Azure AD ikke stopper opp.

**Comment by yngvark** [comment]
I fall det er spesifikke folk vi må ta kontakt med: https://oslokommune.slack.com/archives/C705GLM52/p1676372993455969?thread_ts=1676372889.780169&cid=C705GLM52

**Comment by yngvark** [comment]
Vurder: Neste gang vi må gjøre dette, bør vi påminnes 4mnd i forveien, så vi i minst mulig grad må avbryte det vi må holde på med for å hoppe på denne.

**Comment by yngvark** [comment]
Note to self: Man skal ikke være på VPN når man bruker Kompass: https://oslokommune.slack.com/archives/C705GLM52/p1677848922472599

**Comment by yngvark** [comment]
Runbook: https://docs.google.com/document/d/16sDzpuf5Mb5xwZkFsSkUf7ND-2e9M7lhRY4EFYQ2T9Q/edit#

**Comment by yngvark** [comment]
Kompass-sak er nå opprettet av @eivindlu her: https://saas.smax.no/saw/ess/requestTracking/6167109?TENANTID=583754967

**Comment by yngvark** [comment]
Da er nytt token med expiry 3/6/2024 oversendt UKE.

**Comment by leiacf** [comment]
Usikker på hva som gjenstår i denne? Vente på svar fra UKE eller bare info til alle?

**Comment by yngvark** [comment]
Stemmer, avventet svar fra UKE. Dette har vi nå fått, så lukker saken her og i Kompass.

Trenger ikke gi ut noe info, ting (mao. synch av brukere mot AD) skal bare funke som før i det stille.
