### ISSUE TITLE
Fjern Julius fra all things kjøremiljø 😭

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#106]
Nå som Julius har byttet team bør han fjernes fra forskjellige grupper og kontotilganger.. 

Det står noe info her om hva som skal gjøres: https://docs.google.com/document/d/1CV_Xo6Lai7L-Hv1P6Fw6V9sIbZ_3vNVUfeJAw9RdNlk/

**Comment by haavardeide** [comment]
- [x] gopher
- [x] slack kanaler - valgfritt for Julius å følge med på framover
- [x] ta vekk fra github team: https://github.com/orgs/oslokommune/teams/kjoremiljo/members
- [x] ta vekk som github org.admin - berre vanleg medlem
- [x] PRK - melde ut av OOO_AWS_KJOREMILJO_DEV - snakk med Eivind Lund
- [x] PRK - melde ut av admin gruppa - snakk med Eivind Lund
- [ ] Tilgang til epost: https://docs.google.com/spreadsheets/d/1F2jxw3UihfBWqhg6TS_vQ6kk9FYYRVEu-uTjA7o302Y/edit#gid=1073416811 - melding til Eivind sendt
- [x] Møter - ikkje med på invites
- [x] trello
- [x] miro.com - ingen team der
- [x] ferieavvikling
