### ISSUE TITLE
Rename AWS-kontoer for Okctl

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#108]
# Beskrivelse
Ifølge https://aws.amazon.com/premiumsupport/knowledge-center/change-organizations-name/ ser det ut som det er mulig å rename en konto.

Rename konotene
* okctl-dev
* okctl-prod

til noe mer vettugt. Diskuter i tråden under.

# Motivasjon

Vi har arkivert Okctl og ønsker noe nytt.

**Comment by yngvark** [comment]
Om vi vil følge samme navnekonvensjon som de andre kontoene (to konto pr team), så blir det

* kjoremiljo-dev
* kjoremiljo-prod

**Comment by Kielo87** [comment]
Støtter kjoremiljo-dev og kjoremiljo-prod
