### ISSUE TITLE
Onboarde Anders til AWS admin-oppset

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#127]
# Beskrivelse

* [x] Legge Anders til aws management konto
* [x] Spør i Kjøremiljø-intern om flere vil være med på opplæringen før den utføres
* [x] Gi opplæring i essensielle ting man bør kunne om management. 
* [x] Disse kan brukes som opplæringsmateriale:
* [ ] #132 
* [x] #18 

# Motivasjon

* Spre kompetansen på AWS management
* Dette gir store tilganger og medfører en del ansvar, så da er det greit med opplæring.

**Comment by kmoberg** [comment]
Gjennomført introduksjon.
