### ISSUE TITLE
Fjerne AWS-konto dataplattform-dev

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#132]
# Beskrivelse

https://oslokommune.slack.com/archives/C018EFCSC4W/p1679555232306849

# Motivasjon

Rydde opp. Redusere kostnad.

**Comment by yngvark** [comment]
@kmoberg Sjekke om vi har aws-nuke configfil fra #18.

**Comment by yngvark** [comment]
Runbook: https://docs.google.com/document/d/1xpv1i7F_hLXi1Alsjk1eIhI8ec6ui_Ze_4KBS_DRgvo/edit#heading=h.xy0ampti1xin

**Comment by staticaland** [comment]
Skrur av support på konto 4086-5114-9982.

4086-5114-9982.

**Comment by staticaland** [comment]
Trykker på Close-knappen for dataplattform-dev (#408651149982)

4086-5114-9982

![image](https://user-images.githubusercontent.com/1691190/232056187-8e4de83f-bbdd-4298-b391-5ed7e87e4687.png)

You have successfully requested to close account 'dataplattform-dev' (#408651149982).

**Comment by staticaland** [comment]
Successfully moved the AWS account 'dataplattform-dev' to the organizational unit 'Suspended'.

**Comment by staticaland** [comment]
Jeg fikk ikke gjort steg 10 i https://docs.google.com/document/d/1xpv1i7F_hLXi1Alsjk1eIhI8ec6ui_Ze_4KBS_DRgvo/edit#

Fjerne Permission Sets som er deployet til kontoen i AWS SSO

**Comment by staticaland** [comment]
Kontoen er closed og forsvinner om 90 dager. Kostnad på kontoen er lav.
