### ISSUE TITLE
Figure out what to do with the AWS test organization

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#153]
It seems we have a [test org in AWS](https://oslokommune.slack.com/archives/C018EFCSC4W/p1681372804722689) that Fredrik created. 

The [slack thread](https://oslokommune.slack.com/archives/C018EFCSC4W/p1681372811499259) seems to indicate this can be deleted. 

My suggeston is to get this removed, but keep an eye out in case something breaks (tm).

**Comment by leiacf** [comment]
Extra motivation: If this is removed, we probably won't get two excel sheets from billing anymore, been wondering about that one for a while.

**Comment by kmoberg** [comment]
Requested deletion in Crayon CloudIQ
