### ISSUE TITLE
Figure out what to do with DESIGN.md

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#154]
We have a file called DESIGN.md directly on the root folder of our golden path repository. This file seems to be talking about design principles for the golden path, based on what we had in September: https://github.com/oslokommune/golden-path-iac/blob/main/DESIGN.md

Should this file be moved elsewhere, especially now that we've implemented a new system. It's good to keep for historical purposes, but perhaps not in the root folder? 😀

**Comment by leiacf** [comment]
Discussed this with @yngvark now so adding as an assignee!

**Comment by yngvark** [comment]
Mye av beskrivelsene i dokumentet er ikke lengre relevant, og diskusjonen trenger ikke ligge der. Jeg skal fjerne det straks. I fall vi trenger å se på det i framtiden, så ligger det her: https://github.com/oslokommune/golden-path-iac/blob/6b64ad1b91b08ad083f869271786b613956d0ef1/DESIGN.md
