### ISSUE TITLE
Forbedre organiseringen av SCP-er i Organizations

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#155]
# Beskrivelse

Vi har mange `guardrails-<random id>`, og det er vanskelig å vite hvilken vi skal bruke for å endre ting. Vi bør finne et bedre system for dette.

# Motivasjon

Rydde opp.

**Comment by kmoberg** [comment]
Oppdatering: Vi hadde en gjennomgang for halvannen uke siden og det ser ikke ut pr d.d. som det er noen måte å rename SCP/guard-rails på. De er satt av AWS og dersom du endrer navn på dem vil det detekteres som drift, og Control Tower må inn for å fikse det. Dessverre ingen enkel måte å løse dette på...

**Comment by yngvark** [comment]
Om du ikke har noen andre ideer @kmoberg , kan du bare lukke saken.
