### ISSUE TITLE
Presentasjon om veikart til ledergruppen

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#161]
## Beskrivelse

Vi har blitt bedt om å fortelle mer om veikartet vi har laget og brukertestet i ledergruppemøtet på tirsdag 30.05.2023.

Her er presentasjonen vi jobber med: https://docs.google.com/presentation/d/1C5Fiak6BqY_wifazKb-MpIH21h12OAW5s82_AGu9u24/ 

## Motivasjon

Dele med andre det vi har lært og forbedre det vi har.

**Comment by leiacf** [comment]
Vi brukte opp tiden i ledermøtet før vi fikk presentert arbeidet, så vi skal inn igjen! Oppdaterer issuet når vi har vært hos ledergruppen.
