### ISSUE TITLE
Oppdatere team bilde på labs

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#163]
## Beskrivelse

Må få Sondre med på team bildet og artikkelen ellers

## Motivasjon

Ikke bli utdatert!

## Ting å vurdere

- Hvem skal få tech lead tittelen på bildetekst? 😱 Yngvar? Sondre? Begge? 
- Skal Yngvar fortsatt stå som author. Skal jeg "demote" han til en utvikler i beskrivelsen? 

So many questions.

**Comment by leiacf** [comment]
"Husk at nyansatt skal onboardes som utvikler, og ikke Tech lead" sa Andreas.. 

Så jeg tenker vi kjører utvikler nå, og tech lead når overgangen faktisk skjer.

**Comment by Kielo87** [comment]
Takk! Antok at du sitter på fasiten (som alltid) @leiacf 🙌

**Comment by leiacf** [comment]
Fasit vet jeg ikke, men meninger, det har jeg 😁

**Comment by Kielo87** [comment]
Da har jeg oppdatert team bilde (og bildetekst) på Labs https://labs.oslo.kommune.no/tema/utviklingsopplevelse/team-kjoremiljo-steller-i-stand-utviklingsfesten

Sondre er nå titulert som en utvikler og Yngvar er fortsatt reigning tech lead 👑
