### ISSUE TITLE
Lukk en overflødig helsedata konto i AWS

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#167]
## Beskrivelse 

Helsedata har bedt oss om å lukke en konto som de ikke lengre bruker

Flere detaljer på Slack (som kontoinformasjon): https://oslokommune.slack.com/archives/CV9EGL9UG/p1686229101037249

## Motivasjon

Ha ting ryddig 🧹

**Comment by leiacf** [comment]
Kjempefint om @falense tas med når denne utføres. Vi lukker ikke kontoer såååå ofte så greit at han ser fremgangsmåten.
