### ISSUE TITLE
Velg CMS

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#19]
Vi trenger CMS for å ha et sted å samle dokumentasjonen vår. 

Etter å ha diskutert frem og tilbake så har vi landet på at vi vil forsøke oss med Gitbook.

**Comment by leiacf** [comment]
Jobber med å få godkjent og anskaffet.

- [ ] Snakk med Urd Cecilie om hvordan prosessen foregår
- [ ] Fyll ut skjema Urd Cecilie har kommet med
- [ ] Hvis ROS: Gjennomfør ROS

**Comment by Kielo87** [comment]
Jeg tar over oppgaven og fyller ut skjemaet

**Comment by leiacf** [comment]
Oppgaven ligger nå på vent til UC får tatt den videre..

**Comment by leiacf** [comment]
ETter gjennomgang med UC i møte, samt diskusjon i for i bakken-møte, har vi kommet frem til at vi bruker mdBook intill Origo er klare til å hjelpe oss med legal stuff. Dette kan (vil nok) ta tid, så velger å avslutte dette issuet nå, så får vi heller åpne et nytt når den tid kommer.

**Comment by yngvark** [comment]
https://docs.google.com/spreadsheets/d/1PVRqVN-aeNYwfyDJX5YSNG96o2IWAIXAzFyp_kdkCOU/edit#gid=0

La til Contentful.
