### ISSUE TITLE
Bistå Vitalia i august

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#193]
# Beskrivelse

Inspisere prod miljøet deres, gi de tilbakemelding på dette. 

Finn ut med de hvordan de ønsker å jobbe med dette. Med Veiviser lagde vi en [rapport](https://docs.google.com/document/d/1tIYocGngMlI0dCMZFN8PRO6ULFIQOsjN7hspoDMPM18/edit).

Dette må skje i august eller før midten av august pga deadlines teamet har.

Se [referat](https://docs.google.com/document/d/1vYG9YSwspkb9evgBzae6ceC1uN74ybdp7oAhBXYCSUU/edit) fra planleggingsmøte 05. juli 23 for mer detaljer.

# Motivasjon

Tilfredstillende kvalitet på infrastrukturen til teamet.

**Comment by leiacf** [comment]
Vi har hatt en[ QA på infraen](https://docs.google.com/document/d/1rBgzECOWECSJOxLr-HuKFhg4aBPCaffltuA0IMXW-08/edit) og meldt i fra om dette [på Slack](https://oslokommune.slack.com/archives/C054MHJ0BPU/p1691136999314679?thread_ts=1691041564.417789&cid=C054MHJ0BPU).

Ballen ligger nå hos Vitalia for videre oppfølging.

**Comment by leiacf** [comment]
Lukket etter avtale med Vitalia
