### ISSUE TITLE
Oppdater linting-flyten i golden-path-iac

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#197]
I [dagens møte](https://docs.google.com/document/d/1q9w-uUGseKjWyqaxZl2sgniUPwloM9_FTExG3gq1X54/) ble vi enige om at vi heretter skal linte alle README.md som ligger i /terraform/modules i golden-path-iac. 

Etter å ha lest igjennom repoet nøyere tror jeg vi bør utvide dette til å gjelde i alle fall hele /terraform/, men kanskje også /RFC-KM/ I tillegg har vi README.md og CONTRIBUTING.md direkte på rot.

For å få til dette må sannsynligvis følgende gjøres:

- [x] Få klarhet i hva som skal være med i lintingen heretter
- [x] Utvide scope for hva som innebefattes av dagens linting:
- [x] Legg til /terraform og undermapper (spesielt /modules)
- [x] Legg til /RFC-KM
- [x] Legg til README og CONTRIBUTING på rot
- [x] ignorer .md-filer som ikke er en del av dokumentasjonen (mest sannsynlig CHANGELOG.md, men kanskje også andre). Dette kan gjøres med spesifikke kommandoer for Vale og markdownlint i hver fil. 

Se også https://github.com/oslokommune/golden-path-iac/issues/727

**Comment by leiacf** [comment]
Har stilt oppklarende spørsmål rundt hva som skal lintes her: https://oslokommune.slack.com/archives/C018EFCSC4W/p1691422428555919

**Comment by leiacf** [comment]
Har koppdatert arbeidslista etter diskusjonen på Slack. Issuet bør kunne jobbes med nå.

**Comment by falense** [comment]
https://github.com/oslokommune/golden-path-iac/pull/995

Venter på QA

**Comment by falense** [comment]
Sliter med Github workflows som ikke vil spille på lag. Jobber videre med denne: https://github.com/oslokommune/golden-path-iac/actions/runs/5867604210/job/15908620784

Av en eller annen grunn så finner den ikke filene som er i repoet.
