### ISSUE TITLE
Vurdere Maskinporten-overgang

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#199]
# Beskrivelse

I Sparring-møte 08 aug 23, ble vi enige om å synliggjøre konsekvens av Maskinporten-overgang til Kjøremiljø.

# Motivasjon

Tydeliggjøre konsekvens for beslutningstakere.

**Comment by leiacf** [comment]
Charlotte har kalt inn til en del arbeidsmøter rundt dette for å samskrive med alle involverte. Vi bør vurdere om vi i tilegg har egne møter og / eller hjemmelekser.

Jeg og Charlotte skal ha møte med Ximena 29/8 om dette, så vi har litt tidspress.

**Comment by yngvark** [comment]
Mine notater: https://docs.google.com/document/d/1AfFR-fn7kh9Kul42u_ctxBEmLdYffO0dbW2oFPcqNzE/edit

**Comment by yngvark** [comment]
Da har jeg notert noen tanker i notatene.
