### ISSUE TITLE
Lage presentasjon for TLG møte 28.08.2023

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#200]
## Beskrivelse

Vi møter TLG 28.08.2023 for å snakke om kompetanse ++

Presentasjon https://docs.google.com/presentation/d/1v6DlyVXJZGCifsVhTCihjPvCT4dqmvC6MsUcKj0I_G8/

**Comment by haavardeide** [comment]
Er kompetanse for resten av teamet eit punkt å ta for seg?

At TL/Design/etc forstår kva denne DevOps kulturen og AWS strukturen er og betyr? Slik at det er forståelse i alle ledd.

**Comment by leiacf** [comment]
@haavardeide Det er et godt poeng. Jeg kan nevne det i diskusjonen, men det fortjener kanskje et eget tema? Denne gangen har vi vinklet det mot at spesifikt utviklere trenger mer opplæring i AWS og infrastruktur.

**Comment by Kielo87** [comment]
Jeg skal ha det i bakhodet ✅

**Comment by Kielo87** [comment]
**Kjøremiljø har møtt TLG om onboarding og opplæring**
Dette er [presentasjonen](https://docs.google.com/presentation/d/1v6DlyVXJZGCifsVhTCihjPvCT4dqmvC6MsUcKj0I_G8/edit#slide=id.g559c3dd4b5_0_28) som ble vist.

Nina skal være kontaktperson videre for TLG, som skal ta saken videre.
