### ISSUE TITLE
Jobbe med Maskinporten-grunnlag

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#201]
### Bakgrunn
Origos løsning for integrasjon mot Maskinporten (Origo-Maskinporten) ble laget av et team som nå er nedlagt. Ved nedleggelsen ble det besluttet at siden Origo-Maskinporten er et fellesverktøy passet den best i Kjøremiljø. 

Hittil har løsningen fulgt utviklerne som laget løsningen, men det har lenge vært på trappene at den skal overføres til Kjøremiljø denne høsten.

### Plan

Vi tar en gjennomgang av løsningen sammen med Dataspeilet, med hensikten å få frem et underlag for å diskutere overgangen på nytt med beslutningstakerne. Vi ser på den tekniske løsningen, pros and cons for overgangen, og gir en uttalelse rundt konsekvenser for Origo.

### Motivasjon

Undersøke om beslutningen er tilstrekkelig belyst.
Gjøre det som er best for Origo (samt Kjøremiljø og Dataspeilet) i stort.

### Dokumenter

[Tidligere vurdering rundt Keycloak](https://docs.google.com/document/d/1aAoOeqS-Oj_kkhgpcAW9AKPvmBXVMpKP0_YC2wL2eQM/)
[Møtereferat teknisk gjennomgang](https://docs.google.com/document/d/1wpFIPqOrqi5dGj74zp032iy4kWunaB7GCChTDr4NUn4/)

[Samskrivingsdokument](https://docs.google.com/document/d/1hgG7cXHuvbEXzTVgH54YseOIk4C9DaFAFUEJh6cQN68/)

```[tasklist]
### Oppgaver som må gjøres
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/199
- [x] Sette opp samarbeidsmøter med Dataspeilet
- [x] Få teknisk gjennomgang fra Dataspeilet
- [x] Samskrive underlagsdokument
- [x] Renskrive underlagsdokument
- [x] Legge til de andre dokumentene det henvises til som vedlegg
- [x] Renskrive vurderingsdokumentet (vedlegg 1)
- [x] Legge frem underlaget til Ximena i møte 20. september
```

**Comment by leiacf** [comment]
Det eneste som gjenstår her nå er å legge frem grunnlaget i møte. Lar saken ligge til det er gjort.

**Comment by Kielo87** [comment]
Saken er behandlet og ansvaret for Maskinporten skal ligge hos Dataspeilet.
