### ISSUE TITLE
Utforske AWS Inspector & Trusted Advisor

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/kjoremiljo-admin-issues#202]
# Beskrivelse
AWS har forskjellege verktøy for å kunne køyre automatisk scan av containers/images/kode, bla. AWS Inspector & Trusted Advisor

* Utforsk AWS Inspector & Trusted Advisor og sjå kva dei kan gi oss av oversikt: kan vi seie noko om oppdatering på tvers av team, kva team ikkje gjer, korleis kan vi benytte oss av resultat for å kunne gjere ting for teama proaktivt
* For Trusted Advisor: Vi har alt tilgang til alle sjekkar for produksjonskontoane våre via support-nivået vårt
* Sjå på korleis teama kan bruke desse verktøya 
* Sjå på korleis vi kan bruke verktøya på organisasjons-nivå

# Motivasjon
* Automatiser så masse som mulig
* Bruk verktøy fra AWS som kan gi oss innsikt på kvar vi har problem
* Vi får no tilgang til deep scanning på EC2 instansar og bla CVE & CIS. Vi kan få oversikt og kontroll på ein baseline

**Comment by leiacf** [comment]
Dette ser ut som noe som passer på tasklisten til https://github.com/oslokommune/kjoremiljo-admin-issues/issues/178

**Comment by haavardeide** [comment]
* EC2 deep inspection: https://docs.aws.amazon.com/inspector/latest/user/scanning-ec2.html#deep-inspection%22
* lambda scan: https://docs.aws.amazon.com/inspector/latest/user/scanning-lambda.html#lambda-code-scans
* container scan: https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html

**Comment by haavardeide** [comment]
Plan: 
* Enable på org. nivå
* invite kjoremiljo kontoar
* invite origo-prod
* invite teknologi-dev/prod

**Comment by haavardeide** [comment]
Presantert til team på tysdags demo og dokumentert her: https://docs.google.com/document/d/1vMRpwFPJgLl-5_yRfbnpXfqS-b8TsuO1uFp64JjEXWA/edit

Oppfølging med å få implementert alle warnings og dokumentere bruken er lagt til: https://github.com/oslokommune/kjoremiljo-confidential-issues/issues/63
