### ISSUE TITLE
Communication plan

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#22]
[Kommunikasjonskanaler og kommunikasjonsplan](https://miro.com/app/board/uXjVOrSM6qM=/?share_link_id=716005768094)

**Comment by leiacf** [comment]
Har snakket med Ximena om veien videre her. Vi tar et kort møte for å finne ut av hvilke action points vi har videre.

Ble også enige om at Nina holder innlegg om status i Ledermøte 22/9.

**Comment by Kielo87** [comment]
Satt møte med Ximena på mandag, men jeg er trippelbooket eller noe
