### ISSUE TITLE
Sende sikkerhetsrapport pluss vår kommentar om den til teamene

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#31]
Ref
https://docs.google.com/forms/d/1GV02QOmO_5l4BHHaaMVAMxkzf2jJq1lsYQAmb8mFV6s/edit#responses

Når sikkerhetsgjennomgang av OKCTL er gjort, ønsker vi gjerne å høre om funn

Dokument: https://drive.google.com/drive/u/0/folders/1nswVdMqDZQUTz8vPQ16Y1AYYmsTkeI7n
→ "Sikkerhetstest Origo Kjøremiljø v1"

Nina 31 Aug 2022
>Ingen “gode” måter å dele passordet på en effektiv måte (burde bruke passordmanager, men forstår det slik at ikke alle bruker det).

>Forslag: Send rapport på e-post. Send passord på signal/sms (ja, vet det er tungvindt når det er til mange). Be mottakere om at rapporten holdes innad i teamet.

**Comment by leiacf** [comment]
Snakket med Martin på nytt og fikk lov til å dele passordet på slack. 

Har sendt til følgende team leads med oppfordring om å dele videre med de som trengs:

- Anna (Booking)
- Kaia (Informasjonsflyt)
- Marie (Legevaktmottak)
- Håkon (Veiviser)
- Catalina (Barnehagepris)

**Comment by yngvark** [comment]
Done
