### ISSUE TITLE
Si ifra på #okctl-viktig hvordan fikse TLS 1.0./1.1

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#32]
Avventer merge av [oslokommune/okctl: Pull Request 1009](https://github.com/oslokommune/okctl/pull/1009)

**Comment by leiacf** [comment]
Pull requesten ser ut til å være merget for lenge siden, så litt usikker på hvorfor denne fortsatt ligger på WiP?

**Comment by yngvark** [comment]
Det er lenket til feil pull request, skal være https://github.com/oslokommune/okctl/pull/1003.

Oppgaven er løst med den PR-en, samt melding på Slack: https://oslokommune.slack.com/archives/C02U8HJARLH/p1664517602434569
