### ISSUE TITLE
Midlertidig oversikt over teknologier og tjenester som brukes i Origo

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#40]
Lage en Excel oversikt over hvilke tjenester teamene bruker nå i AWS ++

**Comment by leiacf** [comment]
@Kielo87 Denne kan vel ferdigstilles ved hjelp av det vi fikk ut av superbrukerforum og en dobbeltsjekk med teamene om det stemmer, eller?

**Comment by Kielo87** [comment]
Delvis ja, men den dekker jo ikke alt som de har nå verktøymessig så vi må også kanskje se på oversikten i AWS billing

**Comment by leiacf** [comment]
Er vel egentlig duplikat av #13, så lukker denne.
