### ISSUE TITLE
Tydelig roadmap som er knyttet til tid

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#43]
[Roadmap for Golden Path](https://miro.com/app/board/uXjVOsqs8vY=/?share_link_id=978306041433) på Miro

**Comment by Kielo87** [comment]
Trenger tilbakemeldinger

**Comment by yngvark** [comment]
Her eller i miroen? Jeg la inn en kommentar i Miroen.
