### ISSUE TITLE
Hvordan ser fremtiden ut de neste 4 månedene for Origo-team?

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#51]
Vi har behov til å snakke med alle teamene om fremtidsplanene deres. Nina og Mira tar en prat med team leads med første omgang

### Vi har snakket med
- [x] Barnehagepris
- [x] Veiviser
- [x] Informasjonsflyt
- [x] Vitalia
- [x] Booking
- [x] Min side
- [x] Skjema
- [x] Legevaktmottak

**Trenger ikke å snakke med**
- [x] Dataspeilet
- [x] Oslonøkkelen
- [x] Barnehageplass

**Comment by Kielo87** [comment]
Har sendt innkalling til alle unntatt
- Legevaktmottak
- Oslonøkkelen
- Barnehageplass
- Dataspeilet

Vi har pågående dialog med Legevaktmottak og Barnehageplass. Oslonøkkelen og Dataspeilet skal ikke migrere over til løsningen vår.

**Comment by leiacf** [comment]
Har snakket med:

* Booking
* Informasjonsflyt
* Skjema
* Min Side
* Barnehagepris
* Vitalia
* Barnehageplass (tidligere)

Jobber med å få frem en tidslinje for hva vi har kommet frem til

**Comment by leiacf** [comment]
Vi ombestemte oss om legevaktmottak etter å ha sett på tidslinjen vår

**Comment by leiacf** [comment]
Har nå også snakket med veiviser og oppdatert tidslinjen. Begynner å se bra ut.. Mangler bare legevaktmottak.

**Comment by leiacf** [comment]
Har snakket med legevaktmottak og oppdatert tidslinjen
