### ISSUE TITLE
Research og skriv RFC for CI/CD

### ISSUE THREAD

**Issue by kmoberg** [oslokommune/kjoremiljo-admin-issues#52]
Etter diskusjon med AWS skriver vi en RFC før neste møte 26.09 om vi vil bruke CodePipeline med Build og Deploy for å gjøre bygg og deploy til ECS.

**Comment by yngvark** [comment]
Er målet med denne oppgaven å finne ut av hvilke verktøy vi kan bruke for CI/CD? Eller er det bare å sjekke ut hva de nevnte AWS-tjenestene kan gi oss?

Hvis vi i denne oppgaven ønsker å ta et valg, så må vi undersøke Github actions også.

**Comment by yngvark** [comment]
Et behov vi antakeligvis bør dekke på sikt (ikke sikkert i V1 av brolagt sti), er deploy av feature branches. Det er meldt som behov her: https://docs.google.com/document/d/1CtFN7udACb9vFrnMuYmcKzttId3sdz6RHUryoH8heyg/edit#heading=h.qu99za2jjll7

**Comment by kmoberg** [comment]
@yngvark Tanken var å researche begge deler - hva Code Pipeline kan gi oss enklere enn det Github Actions kan gi oss, spesielt med tanke på deploy til ECS.

**Comment by yngvark** [comment]
Neste oppgave: Sammenstille arbeidsdokument og referat fra superbrukerforum, og lage en markdown i RFC format i golden-path-iac repo
