### ISSUE TITLE
Definer hva teamene trenger av kompetanse før Brolagt sti onboarding

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#59]
# Beskrivelse

Bakgrunn: [Møte - Hvordan onboarde team til Brolagt sti](https://docs.google.com/document/d/1floocpUnVSGiMZ-ZCUHEkIQEkXH6JQo3mhnO-fvfkpw/edit#heading=h.21tp3t18dn1s)

Finn ut av kompetanse. Fyll inn i https://docs.google.com/document/d/1E2_hfXClHRugI3eH-779RDdw-8b9zXE2EGVm9_iWcb8/edit#

# Motivasjon

Uten nødvendig kompetanse får ikke teamene så mye ut av onboardingen, de vil ikke klare å henge med.

**Comment by hranum** [comment]
Jeg vil bruke litt tid på å finne 1 eller 2 gode `terraform` videoer på nettet som tar for seg det aller mest nødvendige

**Comment by hranum** [comment]
Har gjort endringer i dokumentet og avventer svar på undersøkelse rundt MÅ/BØR på kompetansekrav før onboarding. Lukker saken når svarene er kommet inn.

**Comment by hranum** [comment]
Har oppdatert dokumentet og linket til læringsressurser

![Image](https://user-images.githubusercontent.com/17699163/194058847-22f191cf-18e3-4c8e-8091-ba64a71beb5f.png)

Skal vi si dette holder for denne gang, og lukke saken?

**Comment by yngvark** [comment]
Ja ser bra ut!
