### ISSUE TITLE
Fullfør opprettelse av barnehageplass-kontoer

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#60]
Bestilling

barnehageplass-dev: aws-barnehageplass-dev@origo.oslo.kommune.no
barnehageplass-prod: aws-barnehageplass-prod@origo.oslo.kommune.no

Begge desse er satt opp mot "aws kontoer crayon 4" kontoen.

* [x] Sette opp e-post aliaser
* [x] Opprette konto (fra rutine)
* [x] Sørg for at team medlemmene får tilgang til kontoene
* [x] Slett IAM brukerne vi har lagd temporært i barnehageplass-dev kontoen (måtte gjøre det pga [synk issues med AD](https://oslokommune.slack.com/archives/C018EFCSC4W/p1664959104969849))
* [x] Sette supportlevel

**Comment by yngvark** [comment]
AD-gruppe for barnehageplass mangler, har bestilt i fra @eivindlu (som bestiller til UKE / Katalog-teamet)

**Comment by yngvark** [comment]
Alt er gjort bortsett fra å sette på supportlevel. Det er delegert til issue #66.

**Comment by yngvark** [comment]
Blokkert pga AD gruppe ikke havner i AWS hos oss. Eivind er på saken.

**Comment by deifyed** [comment]
Alt skal være på plass nå, bortsett fra supportlevel

**Comment by yngvark** [comment]
Da har jeg fikset resterende punkter.
