### ISSUE TITLE
Oversikt over supporthendelser på #origo-kjøremiljø-support og estimert tidsbruk

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#61]
https://docs.google.com/spreadsheets/d/1gP9Hajo8PeSEsRsBiWAKfqrcD6pqonD34eMX_3bWa3M/edit#gid=357490262

Vi har behov til å estimere hvor mye tid vi bruker på support. Dette skal brukes som nullpunktsmåling

**Comment by leiacf** [comment]
Dokumentet ble greit mottatt i møtet, selv med stor disclaimer om at tallene var usikre. Så tror fint vi kan fortsette å få skrevet ned tallene så langt tilbake i tid vi kommer.

Sannsynligvis lurt å lage en ny fane for alle innkommende saker heretter, og være litt på, så tiden brukt blir mer riktig..

**Comment by leiacf** [comment]
Vi må fnne ut av (og snakke med Ximena) om hvorvidt dette er et av grunntallene som skal opp i møtet med ledergruppen 3. november.

**Comment by leiacf** [comment]
Legger denne også i completed. Regnearket er opprettet, så kan se se senere om det faktisk skal brukes videre.
