### ISSUE TITLE
Undersøkelse: Brukertilfredshet

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#64]
Vi har behov for å få en nullpunksmåling på brukertilfredshet på de teamene som bruker okctl. Vi kjører en ny økt etter at fleste teamene har gått over på brolagt sti for å kunne se hvordan situasjonen har utviklet seg.

**Comment by Kielo87** [comment]
Har begynt arbeidet i mappen her: https://drive.google.com/drive/u/0/folders/1RVytN4yL11h7dfyxb_khczC9G0t4838q

**Comment by Kielo87** [comment]
Vi har en first draft på Google Forms https://docs.google.com/forms/d/12Kcc44A0si75Mc6ri4grH6lReC1Fj172rm4BCguPXXA/ som skal kvalitetssikres og tweakes basert på tilbakemeldinger

Ximena må avklare med høyre makter om når det kan passe å kjøre en spørreundersøkelse

**Comment by leiacf** [comment]
Denne venter nå på utfallet av effekt-møtet. Deretter må vi ha et nytt møte hvor vi tweaker denne og inkorporerer tilbakemeldinger fra Trond som Ximena sitter på.

**Comment by Kielo87** [comment]
Dette må vi finne ut av, vi burde kjøre dette snart om vi ønsker at folk fortsatt husker (på ekte) hvordan det har vært å jobbe med okctl

**Comment by Kielo87** [comment]
Vi fortsetter med arbeidet. Første versjon har blitt brukertestet.

Miro-brett om spørreundersøkelse: https://miro.com/app/board/uXjVMPSxQeY=/?share_link_id=619249213165

Test undersøkelse i Google Forms: https://docs.google.com/forms/d/e/1FAIpQLSd8MySJCXwz8EMKBT8Jf7ueH8xBzGAIBwoEPRWmh7X3XJX7Ww/viewform

Målet er å få ut undersøkelsen i begynnelsen av juni.

**Comment by Kielo87** [comment]
Undersøkelsen er sendt og vi har fått svar. Vi jobber med å bearbeide dataen.

Veien videre

- Designere sorterer funn og lager en første iterasjon av rapport
- Team leads blir invitert til å diskutere funn og tweake rapporten
- Funn blir presentert for teamene / produktområdet
- Funn og tiltak blir presentert i f.eks allmøte

**Comment by Kielo87** [comment]
Svar på brukerundersøkelsen https://docs.google.com/forms/d/1HghBTFbpF_bJOGFNCskI9QcDiDtFWZDj8N783cwceu8/edit#responses

Data strukturert av Maria: https://docs.google.com/spreadsheets/d/1d7xjoJ6lLBj9wLlALoVVmuYGx1rbeA_tsqOCu1gYkF8/edit#gid=1343024110

**Comment by Kielo87** [comment]
Jeg har samlet Kjøremijø-spesifikk data på et MIro-brett https://miro.com/app/board/uXjVMtbI7qk=/?share_link_id=76373518200 

Vi skal bruke brettet etter hvert til å gå gjennom funn og diskutere mulige tiltak 🚧

**Comment by Kielo87** [comment]
Det er feil i datagrunnlaget som ligger på Google Sheets. De gjennomsnittene der er ikke å stole på.

Jeg rydder opp i Miro-brettet vårt. Alt som står der skal stemme https://miro.com/app/board/uXjVMtbI7qk=/?share_link_id=14022456638

**Comment by Kielo87** [comment]
Jeg har oppdatert tallene sånn at de stemmer og prøver å vise fram variasjon også.[ Disse ligger i Miro](https://miro.com/app/board/uXjVMtbI7qk=/?share_link_id=14022456638).

![Image](https://github.com/oslokommune/kjoremiljo-admin-issues/assets/70196851/a472b9a9-0043-4ca0-a7c4-56f2d61eb940)

Nest steg er å analysere tallene litt bedre og skrive litt om noen funn og tiltak (basert på det vi diskuterte også tidligere på demo).

**Comment by leiacf** [comment]
Si ifra hvis du trenger sparring (spesielt siden jeg ikke var på demo)

**Comment by Kielo87** [comment]
Jeg har begynt med å tolke dataen og skrive ned noen funn på [Miro-brettet](https://miro.com/app/board/uXjVMtbI7qk=/?share_link_id=751318169528).

![Image](https://github.com/oslokommune/kjoremiljo-admin-issues/assets/70196851/ccbde2a5-b9c0-4f70-a9b6-e7394af1d80c)

Har koblet noen mulige tiltak mot funnene. Noen av tiltakene er ting som vi allerede gjør. Noen av dem er muligheter for fremtiden. Tror det ligger flere muligheter der som jeg har ikke tenkt på.

Kanskje du @leiacf har noen meninger og vil enten ta en prat med meg eller drodle videre i brettet? :)

**Comment by leiacf** [comment]
Vi kan ta en prat. Noen ganger lettere når man har samtaler om et tema :)

**Comment by Kielo87** [comment]
Vi har tiltak på tilstrekkelig nivå sånn at vi kan kommunisere mot produktområdet. Lukker saken og vi kan eventuelt lage en ny når vi ønsker å bearbeide ting videre. Dette er en viktig tall grunnlag for oss å ta videre.
