### ISSUE TITLE
Gi EY tilgang til egen AWS-konto

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#80]
### Beskrivelse

Gi EY tilganger ved å gjøre følgende:

- Opprette en AD-gruppe (eks EY-sikkerhetstest)
- Legg til Kim Syversen, Ingvild Løes Nilsson og Vegard Wærp i denne
- Opprette en AWS-konto (eks EY-sikkerhetstest
- Gi den opprettede AD-gruppen admintilgang til den opprettede AWS kontoen, og lesetilgang til management kontoen

Bruk runbookene vi har for dette (opprette AD gruppe, opprette AWS konto).

### Motivasjon

EY skal sikkerhetsteste brolagt sti, og det er ønskelig at de gjør dette ved å spinne opp det vi har lagd i brolagt sti.

De skal også teste AWS management-konto oppsettet vårt,

Siden EY setter i gang sikkerhetstestperioden 02. nov, så haster dette (burde vært gjort før, men var en glipp). De har noe å jobbe med selv om de ikke har mulighet til å spinne opp ting i AWS, men de bør få tilganger så snart som mulig.

**Comment by kmoberg** [comment]
Utført

**Comment by yngvark** [comment]
Lesetilgang til mgmt konto ikke nok, de trenger lesetilgang til Control tower også.

https://oslokommune.slack.com/archives/C048ZCNT4NN/p1668415893539329?thread_ts=1667467130.132659&cid=C048ZCNT4NN

**Comment by yngvark** [comment]
Done.

**Comment by leiacf** [comment]
Kan denne lukkes? Og trenger vi et oppfølgingsissue på å fjerne de igjen når jobben er gjort?

**Comment by yngvark** [comment]
Jepp, ligger i https://github.com/oslokommune/kjoremiljo-confidential-issues/issues/8
