### ISSUE TITLE
Dependabot security issues for origo-aws-infrastructure

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/kjoremiljo-admin-issues#96]
# Beskrivelse
Dependabot har lagt til 3 issues i origio-aws-infrastructure https://github.com/oslokommune/origo-aws-infrastructure/security/dependabot som vi bør ta ein kikk på.

# Motivasjon
Security er #1🥇

**Comment by yngvark** [comment]
Koden er ikke i bruk, så dette kan kan prioriteres ned.

**Comment by haavardeide** [comment]
Ingen gjenståande issues, lukker denne
