### ISSUE TITLE
Oppgrader ghost.org - trykk på upgrade knapp

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#98]

**Comment by deifyed** [comment]
Ferdig trykket

**Comment by deifyed** [comment]
![image](https://user-images.githubusercontent.com/1145370/213410588-09976ed8-9a6f-4235-9e0f-683dad991172.png)

Kom et par feil, men siden LGTM, så kan ignorere feilene
